FROM nginx:alpine

COPY ./ /usr/share/nginx/html

# COPY ./nginx.conf /etc/nginx/conf.d/default.conf








#WORKDIR /app


#COPY package*.json ./


#RUN npm install


#COPY . .


#RUN npm run build


#FROM nginx:alpine
#COPY --from=0 /app/build /usr/share/nginx/html

#COPY index.html /usr/share/nginx/html
#COPY home.html /usr/share/nginx/html
#COPY css/home.css /usr/share/nginx/html/css