FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app/chmury
COPY chmury /app/chmury

RUN mvn clean install

FROM openjdk:17-alpine

WORKDIR /app
COPY --from=build /app/chmury/target/demo-0.0.1-SNAPSHOT.jar /app/demo-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]